package main

import (
	"context"
	"go/ast"
	"os"

	sitter "github.com/tree-sitter/go-tree-sitter"
	java "github.com/tree-sitter/tree-sitter-java/bindings/go"
)

// ParseSourceAst parses a given source file and returns the tree-sitter root
// node for the AST associated with that file
func ParseSourceAst(fileName string) (*sitter.Node, []byte) {
	parser := sitter.NewParser()
	parser.SetLanguage(sitter.NewLanguage(java.Language()))

	sourceCode, err := os.ReadFile(fileName)
	if err != nil {
		panic(err)
	}

	tree := parser.ParseCtx(context.Background(), sourceCode, nil)

	return tree.RootNode(), sourceCode
}

func ParseAst(fileName string) ast.Node {
	root, source := ParseSourceAst(fileName)
	return ParseNode(root, source, Ctx{}).(ast.Node)
}

// // This tests the increment and decrement handling on increment and decrement
// // statements, as well as expressions
// func TestIncDec(t *testing.T) {
// 	var generated bytes.Buffer
// 	err := printer.Fprint(&generated, token.NewFileSet(), ParseAst("testfiles/IncrementDecrement.java"))
// 	if err != nil {
// 		t.Fatal(err)
// 	}
// 	t.Log(generated.String())
// }
//
// // This tests the variable assignment handling, using it as a statement as
// // well as an expression
// func TestAssignments(t *testing.T) {
// 	var generated bytes.Buffer
// 	err := printer.Fprint(&generated, token.NewFileSet(), ParseAst("testfiles/VariableAssignments.java"))
// 	if err != nil {
// 		t.Fatal(err)
// 	}
// 	t.Log(generated.String())
// }
//
// // This tests two alternate ways of calling the new constructor
// func TestAlternateNewCall(t *testing.T) {
// 	var generated bytes.Buffer
// 	err := printer.Fprint(&generated, token.NewFileSet(), ParseAst("testfiles/SelectorNewExpression.java"))
// 	if err != nil {
// 		t.Fatal(err)
// 	}
// 	t.Log(generated.String())
// }
//
// // This tests for various combinations of init, cond, and post parts of for loops
// func TestScrambledForLoops(t *testing.T) {
// 	var generated bytes.Buffer
// 	err := printer.Fprint(&generated, token.NewFileSet(), ParseAst("testfiles/ScrambledForLoops.java"))
// 	if err != nil {
// 		t.Fatal(err)
// 	}
// 	t.Log(generated.String())
// }
//
// // This tests for the correct handling of generics (Implemented with go 1.18)
// func TestGenericLinkedlist(t *testing.T) {
// 	var generated bytes.Buffer
// 	err := printer.Fprint(&generated, token.NewFileSet(), ParseAst("testfiles/GenericLinkedList.java"))
// 	if err != nil {
// 		t.Fatal(err)
// 	}
// 	t.Log(generated.String())
// }
//
// func TestConditionOrdering(t *testing.T) {
// 	var generated bytes.Buffer
// 	err := printer.Fprint(&generated, token.NewFileSet(), ParseAst("testfiles/ConditionOrdering.java"))
// 	if err != nil {
// 		t.Fatal(err)
// 	}
// 	t.Log(generated.String())
// }
